### ISSUE TITLE
Covariance matrix of the bi-variate Gaussians

### ISSUE THREAD

**Issue by stratomaster31** [nachiket92/conv-social-pooling#10]
It seems that the covariance matrix of the bi-variate Gaussian is assumed to be diagonal, isn't it? isn't it a strong assumption?

**Comment by nachiket92** [comment]
It isn't, the model outputs the correlation coefficient in addition to the means and standard deviations

**Comment by stratomaster31** [comment]
Ok, you're right, I mixed Up with your other publicación "Multi-Modal Trajectory Prediction of Surrounding Vehicles with Maneuver based LSTMs"
