### ISSUE TITLE
Dataset Problem

### ISSUE THREAD

**Issue by Nick-pick** [nachiket92/conv-social-pooling#14]
First of all, this is a fantastic work！
I have downloaded ‘Next_Generation_Simulation__NGSIM__Vehicle_Trajectories_and_Supporting_Data.csv’ dataset， but it can't match your code. I heard that the dataset had been updated. 
So,  could you please give us a dataset link which includes 6 txt? Or just give us your dataset detail format. I know you mentioned some in preprocess_data.m, but that is too rough. Or just upload example txt, please!

**Comment by GilgameshD** [comment]
you can download the datasets of i80 and US101 from this link:
https://data.transportation.gov/Automobiles/Next-Generation-Simulation-NGSIM-Vehicle-Trajector/8ect-6jqj

Click 'show more' and download 'US-101-LosAngeles-CA.zip' and 'I-80-Emeryville-CA.zip'. All of these six .txt are included.
