### ISSUE TITLE
Why use ''mashed_scatter_" before conv social pooling in the model?

### ISSUE THREAD

**Issue by RomanticLeon** [nachiket92/conv-social-pooling#17]
1. Why use ''mashed_scatter_" before conv social pooling in the model? How to get mash from data?
2. The neighbor's pass position data is converted a tensor('nbrs') input to the model? But in the paper, every neighbor's position is inputted a corresponding LSTM.

**Comment by nachiket92** [comment]
masked_scatter allows for more efficient batching for the encoder LSTMs and the conv social pooling layers during training. There will typically be a different number of neighboring vehicles for each training instance. During the forward pass, all neighboring vehicles in a minibatch are pooled together and processed by the encoder LSTM. The masked_scatter function then places the LSTM states for each vehicle at the appropriate cell location, for the appropriate training instance.
