### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by shakthisharavanan** [nachiket92/conv-social-pooling#2]
Hey thanks for sharing the code. Any plan on releasing the preprocessed dataset. The .mat files?

**Comment by yikang-li** [comment]
Looking forward to the dataset!

Thanks!

**Comment by nachiket92** [comment]
Added script for pre-processing the raw NGSIM text files

**Comment by mprannoy** [comment]
@nachiket92, the script you provided uses preprocessed text files to generate the .mat files. Could you provide code to generate those text files? Or even the preprocessed text files should be fine.
