### ISSUE TITLE
evaluate.py

### ISSUE THREAD

**Issue by beyond96** [nachiket92/conv-social-pooling#21]
Hi,
In the 'evaluate' program, what are the meanings of the two parameters, 'in_length = 16' and 'out_length = 25'? Don't we want to predict the vehicle trajectory in the next 5s? Why 'out'_length = 25?

**Comment by kshitij002** [comment]
hi @beyond96 were you able to crack why the out_length = 25, even though we have to predict for the next 5 seconds?? Also the **evaluate.py** outputs the tensor of size 25, could you help us @nachiket92  ??

**Comment by nachiket92** [comment]
The sampling rate used is 5 Hz. Thus the input is the past 15 locations + the current location (3 sec history), and the prediction has 25 locations corresponding to 5 sec.

**Comment by kshitij002** [comment]
how did you deduced the result table reported in publication, from the tensor with prediction 25 location for corresponding to 5 sec? Looking forward to hear from you soon. thanks for your valuable time :)

**Comment by nachiket92** [comment]
That would be the last (25th) value of the tensor

**Comment by kshitij002** [comment]
I am so sorry I guess I couldn't express my doubts to you in a clear manner.
I am concerned about the results reported in the table, how did you report the values of NLL/RMSE for all the (t+5) seconds from the tensor of 25 size. 
Looking to hear from you soon, thanks for your valuable time!!
![oie_y21TSecIeemb](https://user-images.githubusercontent.com/55188228/75105105-31634200-5637-11ea-957a-8177a34ea77f.png)

**Comment by DataDemystifier** [comment]
It is because of the sampling rate of 5 Hz like was already mentioned by the author of the paper and repository.
The tensor has length 25 and therefore the values correspond to the following sequence of times: [0.2s, 0.4s, 0.6s, 0.8s, 1.0s, ... , 4.8s, 5.0s]

**Comment by kshitij002** [comment]
@DunkDream Thanks a lot

**Comment by rrryan2016** [comment]
For data in NGSIM, the shape of both `fut` and `fut_pred` is `shape of fut: torch.Size([25, 32, 2])`. Regarding to the conversation above, `25` means the following 5 second, but what does `32` mean?
Thanks in advance
