### ISSUE TITLE
Standard deviation in prediction decreases for points further in the future

### ISSUE THREAD

**Issue by maxge089** [nachiket92/conv-social-pooling#23]
The figure below shows the bivariant gauss distribution of the model's prediction. It contains the 25 timesteps of the most likely maneuver (fut_pred_max). The model was trained with default settings on the NGSIM data set as described. 
As you see in the figure, predicted points that are nearer in the future have a higher variance than points that are further in the future. Looking at the pure number confirms this.

How is this possible? Usually, the further the prediction is in the future the less certain you are about the exact position. So the variance should increase over time. Any help is appreciated!

![soc_pool](https://user-images.githubusercontent.com/25860727/74931631-4f833500-53e0-11ea-834c-60d2ece3ff39.png)

**Comment by maxge089** [comment]
Maybe the following figure makes it a bit clearer. Starting point is on the top of the image.
I am also wondering about the very small variances in driving direction compared to the lateral variances...
![soc_pred](https://user-images.githubusercontent.com/25860727/75031855-7b1d2280-54a7-11ea-9866-f52e6516ef5f.png)

**Comment by nachiket92** [comment]
Are you directly using the model outputs for the plot? The model outputs the reciprocal of standard deviations.

**Comment by maxge089** [comment]
Thanks for your answer! That explains a lot...
Is there a reason for using the reciprocals?
Where is it defined? I guess only by the NLL loss, am I right?

**Comment by nachiket92** [comment]
Yes, it's defined purely by the NLL loss. sigX and sigY are just constrained to be positive. 
If all multiplications in the NLL expression with sigX or sigY were swapped with divisions, the interpretation of the model's outputs would be the standard deviations rather than their reciprocals.
