### ISSUE TITLE
NLL loss has negative values

### ISSUE THREAD

**Issue by maxge089** [nachiket92/conv-social-pooling#25]
When evaluating my trained model with NLL as metric, I realize negative values for early timesteps (such as -3.27 at 1 second). This would my predicted probability for the gt trajectory point is in the area of 1000 instead of a maximum of 1. I trained the model on a custom dataset and not on NGSIM. Any ideas where this comes from?

**Comment by nachiket92** [comment]
Likelihoods are not probabilities and can have a value greater than 1
