### ISSUE TITLE
Inconsistency between X and Y loss

### ISSUE THREAD

**Issue by AmitaiPerlstein** [nachiket92/conv-social-pooling#26]
utils lines 170, 172 (for feet, meters respectively) have 
0.5*torch.pow(sigY, 2)*torch.pow(y-muY, 2)   for Y
but 
torch.pow(sigX, 2) * torch.pow(x - muX, 2)    for X

**Comment by nachiket92** [comment]
Both terms have the 0.5 multiplicative factor.

Edit: Ah yes, you're right there was still another typo. The 0.5 factor was outside the bracket for both terms, but was repeated inside for the Y term. This has been fixed. Thanks!
