### ISSUE TITLE
How to get the raw input files?

### ISSUE THREAD

**Issue by fuhuan26** [nachiket92/conv-social-pooling#29]
Hi, I couldn't find the below files from NGSIM website. Could you provide me the link for those data? Thanks! 

us101_1 = 'raw/us101-0750-0805.txt';
us101_2 = 'raw/us101-0805-0820.txt';
us101_3 = 'raw/us101-0820-0835.txt';
i80_1 = 'raw/i80-1600-1615.txt';
i80_2 = 'raw/i80-1700-1715.txt';
i80_3 = 'raw/i80-1715-1730.txt';

**Comment by CuttlefishXuan** [comment]
Have you found it?

**Comment by fuhuan26** [comment]
> Have you found it?

No luck so far.

**Comment by cpacker** [comment]
You can download the files using the instructions here (though you'll have to rename them or change the paths): https://github.com/apple/ml-multiple-futures-prediction#how-to-obtain-ngsim-data
