### ISSUE TITLE
Result of the evaluate.py

### ISSUE THREAD

**Issue by MPCheng-ZW** [nachiket92/conv-social-pooling#37]
Thanks for your contribution.
I have a question about the result of evaluate.py.
Why do I get a tensor after I run the evaluate.py? 
And my result is as follows.
In my opinion, the result should be the values of loss and accuracy as well as the results of train.py.
<img width="1214" alt="Result of the evaluate" src="https://user-images.githubusercontent.com/73774196/209474867-c638abcc-f8ab-407a-b986-6712e1e870fe.png">

**Comment by jchen106** [comment]
do you konw it now,?

**Comment by Leeyhhh** [comment]
> do you konw it now,?
> 你现在知道了吗？

hi do you konw it now?

> do you konw it now,?
> 你现在知道了吗？

hi, do you konw it now?
