### ISSUE TITLE
Text files used in preprocessing not provided

### ISSUE THREAD

**Issue by mprannoy** [nachiket92/conv-social-pooling#8]
@nachiket92, the script you provided uses preprocessed text files to generate the .mat files. Could you provide code to generate those text files? Or even the preprocessed text files should be fine.

**Comment by mprannoy** [comment]
My bad, I was misled by the changed names of the input files. The input is the raw files from the website.

**Comment by codyreading** [comment]
@mprannoy Were you able to find the raw files? The old website is down, and the new csv file doesn't seem to fit the same format

**Comment by mprannoy** [comment]
@codyreading Yes, you can find them [here](https://data.transportation.gov/Automobiles/Next-Generation-Simulation-NGSIM-Vehicle-Trajector/8ect-6jqj). You have to scroll down and click on "show more", where you will find the zip files to download.

**Comment by codyreading** [comment]
@mprannoy how long did the preprocessing script take to run. I've been running it for over 36 hours with my Ryzen 5 1600 and still hasn't finished

**Comment by fuhuan26** [comment]
> @codyreading Yes, you can find them [here](https://data.transportation.gov/Automobiles/Next-Generation-Simulation-NGSIM-Vehicle-Trajector/8ect-6jqj). You have to scroll down and click on "show more", where you will find the zip files to download.
Hi, I downloaded the zip files and it contains some trajectory data.txt, which are not the same as the raw .txt files. Do we still have the access to those raw.txt files nowadays? Thanks.
